create sequence kategorie_osiagniec_seq start with 1 increment by 50;
create sequence kryteria_oceny_seq start with 1 increment by 50;
create sequence oceny_seq start with 1 increment by 50;
create sequence okres_rozliczeniowy_seq start with 1 increment by 50;
create sequence osiagniecia_seq start with 1 increment by 50;
create sequence pod_kategorie_seq start with 1 increment by 50;
create sequence pracownicy_seq start with 1 increment by 50;
create sequence pracownik_stanowiska_seq start with 1 increment by 50;
create sequence rodzaje_dzialalnosci_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence stopnie_naukowe_seq start with 1 increment by 50;
create sequence wnioski_seq start with 1 increment by 50;
create table kategorie_osiagniec (id_kategoria_osiagniec bigint not null, id_rodzaj_dzialalnosci bigint not null, nazwa_kategorii varchar(255), primary key (id_kategoria_osiagniec));
create table kryteria_oceny (czy_na_stanowisku_kierowniczym boolean, czy_posiada_stopien_naukowy boolean, prog_ocenyzwyroznieniemdo integer, prog_ocenyzwyroznieniemnb integer, prog_pozytywnej_ocenydo integer, prog_pozytywnej_ocenynb integer, id_kryterium bigint not null, id_rodzaj_dzialalnosci bigint not null, primary key (id_kryterium));
create table oceny (ilosc_punktow integer, data timestamp(6), id_oceny bigint not null, id_pracownika bigint, id_wniosku bigint, wniosek_id_wniosku bigint, nazwa varchar(255), primary key (id_oceny));
create table okres_rozliczeniowy (id_okresu bigint not null, koniec timestamp(6), poczatek timestamp(6), primary key (id_okresu));
create table osiagniecia (czy_zatwierdzone boolean, ilosc_punktow integer, data timestamp(6), id_osiagniecia bigint not null, id_pod_kategorii bigint, id_pracownika bigint, id_wniosku bigint, nazwa varchar(255), primary key (id_osiagniecia));
create table pod_kategorie (max_punktow integer, min_punktow integer, id_kategoria_osiagniec bigint not null, id_kategorii bigint, id_pod_kategorii bigint not null, nazwa varchar(255), primary key (id_pod_kategorii));
create table pracownicy (id_oceny bigint not null, id_pracownika bigint not null, id_rodzaj_dzialalnosci bigint, id_roli bigint, id_stanowiska bigint, id_stopnia_naukowego bigint, id_wniosku bigint not null, email varchar(255), imie varchar(255), nazwisko varchar(255), primary key (id_pracownika));
create table pracownik_stanowiska (id_stanowiska bigint not null, nazwa varchar(255), primary key (id_stanowiska));
create table rodzaje_dzialalnosci (id_rodzaj_dzialalnosci bigint not null, nazwa varchar(255), primary key (id_rodzaj_dzialalnosci));
create table role (id_roli bigint not null, nazwa varchar(255), primary key (id_roli));
create table stopnie_naukowe (id_stopnia_naukowego bigint not null, nazwa varchar(255), primary key (id_stopnia_naukowego));
create table wnioski (id_okresu bigint, id_pracownika bigint, id_wniosku bigint not null, primary key (id_wniosku));
alter table if exists kategorie_osiagniec add constraint FKjgfxp2aobfxv7bin8isflt448 foreign key (id_rodzaj_dzialalnosci) references rodzaje_dzialalnosci;
alter table if exists kryteria_oceny add constraint FKhis5u8kypbmcvffrcx47qqf3g foreign key (id_rodzaj_dzialalnosci) references rodzaje_dzialalnosci;
alter table if exists oceny add constraint FK5cypp09d2b4j2in7x5lj9xqyo foreign key (id_wniosku) references wnioski;
alter table if exists osiagniecia add constraint FKjm334q4sm73x8txeeub53cdd9 foreign key (id_pod_kategorii) references pod_kategorie;
alter table if exists osiagniecia add constraint FK12ntxx11uayj29ag5iojadpb7 foreign key (id_pracownika) references pracownicy;
alter table if exists osiagniecia add constraint FKc0qrpesg2rep8tqnmvyww0hm0 foreign key (id_wniosku) references wnioski;
alter table if exists pod_kategorie add constraint FKp9q8mbe3n1m9n67vswcfsa7ys foreign key (id_kategoria_osiagniec) references kategorie_osiagniec;
alter table if exists pracownicy add constraint FKs2rlb6mtjab1fai0l8oy9nfmn foreign key (id_oceny) references oceny;
alter table if exists pracownicy add constraint FKjeigc55nu7ichm9ktbne2tbau foreign key (id_stanowiska) references pracownik_stanowiska;
alter table if exists pracownicy add constraint FKaukyxf6cp5igtah82964nmc34 foreign key (id_rodzaj_dzialalnosci) references rodzaje_dzialalnosci;
alter table if exists pracownicy add constraint FK8q5cws2lu4becncbb8hndd1n7 foreign key (id_roli) references role;
alter table if exists pracownicy add constraint FKfbehr259ggtd7egks3wmqegg6 foreign key (id_stopnia_naukowego) references stopnie_naukowe;
alter table if exists pracownicy add constraint FK572xt2iqg0a1u1g67xuyipa8l foreign key (id_wniosku) references wnioski;
alter table if exists wnioski add constraint FKgq87dh57221m408ug61md25ik foreign key (id_okresu) references okres_rozliczeniowy;
